[project]
name = "embedding-axis"
version = "0.1.0"
description = "Compare sample's embedding distance from reference embeddings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.78.0",
]
